spring.application.name=gym-weight
debug=true
spring.thymeleaf.cache=false
server.port=9091
logging.level.org.thymeleaf=DEBUG
logging.level.org.springframework.web.servlet.view.thymeleaf=DEBUG
spring.datasource.url=jdbc:your_dbms
spring.datasource.username=your_user
spring.datasource.password=-your_password